volumes:
  readeck-data:
  readeck-db:

services:
  postgres:
    image: postgres:17
    environment:
      - POSTGRES_DB=readeck
      - POSTGRES_USER=readeck
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - readeck-db:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U readeck -d readeck"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    env_file: ".env"

  app:
    image: codeberg.org/readeck/readeck:latest
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    ports:
      - "8083:8000"
    environment:
      - READECK_DATABASE_SOURCE=postgres://readeck:${POSTGRES_PASSWORD}@postgres/readeck
      - READECK_LOG_LEVEL=info
      - READECK_SERVER_HOST=0.0.0.0
      - READECK_SERVER_PORT=8000
    volumes:
      - readeck-data:/readeck
    restart: unless-stopped
    networks:
      - internal
    healthcheck:
      test: ["CMD", "/bin/readeck", "healthcheck", "-config", "config.toml"]
      interval: 30s
      timeout: 2s
      retries: 3
    env_file: ".env"

networks:
  internal:
    driver: bridge
    
